dataSources:
  ds_0: !!com.zaxxer.hikari.HikariDataSource
    username: root
    password:
    jdbcUrl: jdbc:mysql://ss.benchmark.rangerouting.shardingmasterslaveencrypt.master.ds0:3306/baitiao_test?serverTimezone=UTC&useSSL=false
    driverClassName: com.mysql.jdbc.Driver
    connectionTimeout: 30000
    idleTimeout: 60000
    maxLifetime: 1800000
    maximumPoolSize: 200
    dataSourceProperties:
      cachePrepStmts: true
      prepStmtCacheSize: 250
      prepStmtCacheSqlLimit: 2048
      useLocalSessionState: true
      rewriteBatchedStatements: true
      cacheResultSetMetadata: true
      cacheServerConfiguration: true
      elideSetAutoCommits: true
      maintainTimeStats: false
      netTimeoutForStreamingResults: 0
      useServerPrepStmts: true
  ds_0_slave_0: !!com.zaxxer.hikari.HikariDataSource
    username: root
    password:
    jdbcUrl: jdbc:mysql://ss.benchmark.rangerouting.shardingmasterslaveencrypt.slave.ds0:3306/baitiao_test?serverTimezone=UTC&useSSL=false
    driverClassName: com.mysql.jdbc.Driver
    connectionTimeout: 30000
    idleTimeout: 60000
    maxLifetime: 1800000
    maximumPoolSize: 200
    dataSourceProperties:
      cachePrepStmts: true
      prepStmtCacheSize: 250
      prepStmtCacheSqlLimit: 2048
      useLocalSessionState: true
      rewriteBatchedStatements: true
      cacheResultSetMetadata: true
      cacheServerConfiguration: true
      elideSetAutoCommits: true
      maintainTimeStats: false
      netTimeoutForStreamingResults: 0
      useServerPrepStmts: true
  ds_1: !!com.zaxxer.hikari.HikariDataSource
    username: root
    password:
    jdbcUrl: jdbc:mysql://ss.benchmark.rangerouting.shardingmasterslaveencrypt.master.ds1:3306/baitiao_test?serverTimezone=UTC&useSSL=false
    driverClassName: com.mysql.jdbc.Driver
    connectionTimeout: 30000
    idleTimeout: 60000
    maxLifetime: 1800000
    maximumPoolSize: 200
    dataSourceProperties:
      cachePrepStmts: true
      prepStmtCacheSize: 250
      prepStmtCacheSqlLimit: 2048
      useLocalSessionState: true
      rewriteBatchedStatements: true
      cacheResultSetMetadata: true
      cacheServerConfiguration: true
      elideSetAutoCommits: true
      maintainTimeStats: false
      netTimeoutForStreamingResults: 0
      useServerPrepStmts: true
  ds_1_slave_1: !!com.zaxxer.hikari.HikariDataSource
    username: root
    password:
    jdbcUrl: jdbc:mysql://ss.benchmark.rangerouting.shardingmasterslaveencrypt.slave.ds1:3306/baitiao_test?serverTimezone=UTC&useSSL=false
    driverClassName: com.mysql.jdbc.Driver
    connectionTimeout: 30000
    idleTimeout: 60000
    maxLifetime: 1800000
    maximumPoolSize: 200
    dataSourceProperties:
      cachePrepStmts: true
      prepStmtCacheSize: 250
      prepStmtCacheSqlLimit: 2048
      useLocalSessionState: true
      rewriteBatchedStatements: true
      cacheResultSetMetadata: true
      cacheServerConfiguration: true
      elideSetAutoCommits: true
      maintainTimeStats: false
      netTimeoutForStreamingResults: 0
      useServerPrepStmts: true
  ds_2: !!com.zaxxer.hikari.HikariDataSource
    username: root
    password:
    jdbcUrl: jdbc:mysql://ss.benchmark.rangerouting.shardingmasterslaveencrypt.master.ds2:3306/baitiao_test?serverTimezone=UTC&useSSL=false
    driverClassName: com.mysql.jdbc.Driver
    connectionTimeout: 30000
    idleTimeout: 60000
    maxLifetime: 1800000
    maximumPoolSize: 200
    dataSourceProperties:
      cachePrepStmts: true
      prepStmtCacheSize: 250
      prepStmtCacheSqlLimit: 2048
      useLocalSessionState: true
      rewriteBatchedStatements: true
      cacheResultSetMetadata: true
      cacheServerConfiguration: true
      elideSetAutoCommits: true
      maintainTimeStats: false
      netTimeoutForStreamingResults: 0
      useServerPrepStmts: true
  ds_2_slave_2: !!com.zaxxer.hikari.HikariDataSource
    username: root
    password:
    jdbcUrl: jdbc:mysql://ss.benchmark.rangerouting.shardingmasterslaveencrypt.slave.ds2:3306/baitiao_test?serverTimezone=UTC&useSSL=false
    driverClassName: com.mysql.jdbc.Driver
    connectionTimeout: 30000
    idleTimeout: 60000
    maxLifetime: 1800000
    maximumPoolSize: 200
    dataSourceProperties:
      cachePrepStmts: true
      prepStmtCacheSize: 250
      prepStmtCacheSqlLimit: 2048
      useLocalSessionState: true
      rewriteBatchedStatements: true
      cacheResultSetMetadata: true
      cacheServerConfiguration: true
      elideSetAutoCommits: true
      maintainTimeStats: false
      netTimeoutForStreamingResults: 0
      useServerPrepStmts: true
  ds_3: !!com.zaxxer.hikari.HikariDataSource
    username: root
    password:
    jdbcUrl: jdbc:mysql://ss.benchmark.rangerouting.shardingmasterslaveencrypt.master.ds3:3306/baitiao_test?serverTimezone=UTC&useSSL=false
    driverClassName: com.mysql.jdbc.Driver
    connectionTimeout: 30000
    idleTimeout: 60000
    maxLifetime: 1800000
    maximumPoolSize: 200
    dataSourceProperties:
      cachePrepStmts: true
      prepStmtCacheSize: 250
      prepStmtCacheSqlLimit: 2048
      useLocalSessionState: true
      rewriteBatchedStatements: true
      cacheResultSetMetadata: true
      cacheServerConfiguration: true
      elideSetAutoCommits: true
      maintainTimeStats: false
      netTimeoutForStreamingResults: 0
      useServerPrepStmts: true
  ds_3_slave_3: !!com.zaxxer.hikari.HikariDataSource
    username: root
    password:
    jdbcUrl: jdbc:mysql://ss.benchmark.rangerouting.shardingmasterslaveencrypt.slave.ds3:3306/baitiao_test?serverTimezone=UTC&useSSL=false
    driverClassName: com.mysql.jdbc.Driver
    connectionTimeout: 30000
    idleTimeout: 60000
    maxLifetime: 1800000
    maximumPoolSize: 200
    dataSourceProperties:
      cachePrepStmts: true
      prepStmtCacheSize: 250
      prepStmtCacheSqlLimit: 2048
      useLocalSessionState: true
      rewriteBatchedStatements: true
      cacheResultSetMetadata: true
      cacheServerConfiguration: true
      elideSetAutoCommits: true
      maintainTimeStats: false
      netTimeoutForStreamingResults: 0
      useServerPrepStmts: true

shardingRule:
  tables:
    sbtest:
      actualDataNodes: ms_ds_${0..2}.sbtest${0..99}
      databaseStrategy:
        inline:
          shardingColumn: id
          algorithmExpression: ms_ds_${id % 3}
      keyGenerator:
        type: SNOWFLAKE
        column: id
      tableStrategy:
        inline:
          shardingColumn: k
          algorithmExpression: sbtest${k % 100}
  bindingTables:
    - sbtest

  masterSlaveRules:
    ms_ds_0:
      masterDataSourceName: ds_0
      slaveDataSourceNames:
        - ds_0_slave_0
      loadBalanceAlgorithmType: ROUND_ROBIN
    ms_ds_1:
      masterDataSourceName: ds_1
      slaveDataSourceNames:
        - ds_1_slave_1
      loadBalanceAlgorithmType: ROUND_ROBIN
    ms_ds_2:
      masterDataSourceName: ds_2
      slaveDataSourceNames:
        - ds_2_slave_2
      loadBalanceAlgorithmType: ROUND_ROBIN
    ms_ds_3:
      masterDataSourceName: ds_3
      slaveDataSourceNames:
        - ds_3_slave_3
      loadBalanceAlgorithmType: ROUND_ROBIN

  encryptRule:
    tables:
      sbtest:
        columns:
          pwd:
            cipherColumn: c
            encryptor: encryptor_aes
          name:
            cipherColumn: pad
            encryptor: encryptor_md5
    encryptors:
      encryptor_aes:
        type: aes
        props:
          aes.key.value: 123456abc
      encryptor_md5:
        type: md5

props:
  max.connections.size.per.query: 2
  acceptor.size: 200  # The default value is available processors count * 2.
  executor.size: 200  # Infinite by default.
  query.with.cipher.column: true
  sql.show: false
  allow.range.query.with.inline.sharding: false
  check.table.metadata.enabled: false
